RK = "models/roadkill/fallout/clutter/aid/"
FNV = "models/mosi/fnv/props/health/"
F4 = "models/mosi/fallout4/props/aid/"

INJ = "phoenix/itm/npc_human_using_stimpak.mp3"
PILL = "phoenix/itm/npc_human_using_radx_01.mp3"
JET = "phoenix/itm/npc_human_using_jet.mp3"
PSYCHO = "phoenix/itm/npc_human_using_psycho_01.mp3"
RADAWAY = "phoenix/itm/npc_human_using_radaway.mp3"
MORPHINE = "phoenix/itm/ui_surgery_morphine_01.mp3"

# The Stealth Boy's own activation whine, from `af_additional_weapons_models`.
# Not a swallow: it is a wrist device you switch on, and the gulp it used to
# make was the generic pill sound standing in for one that turned out to be
# installed all along.
STEALTHBOY = "rhys/fx/items/stealth/obj_stealthboy_activate_01.mp3"

# (uniqueID, name, model, description, fields)
CHEMS = [
# ---- healing, no addiction -------------------------------------------------
("aid_stimpak", "Stimpak", FNV + "stimpak.mdl",
 "A syringe of healing agent. The wasteland answer to almost everything.",
 dict(heal=40, sound=INJ, healTime=4, useEffect="inject")),
("aid_superstimpak", "Super Stimpak", FNV + "superstimpak.mdl",
 "A stronger stimpak. Mends more, and takes something out of you doing it.",
 dict(heal=100, sound=INJ, buffs=[("END", -1, 60)], healTime=5, useEffect="inject")),
("aid_stimpak_auto", "Auto-Inject Stimpak", FNV + "stimpak_auto.mdl",
 "A stimpak with a pressure trigger. Goes in through most things.",
 dict(heal=60, sound=INJ, healTime=2, useEffect="inject")),
("aid_healingpowder", "Healing Powder", RK + "healingpowder.mdl",
 "Ground broc flower and xander root. Tribal medicine, and it works.",
 dict(heal=25, sound=PILL, buffs=[("PER", -1, 90)], healTime=6, useEffect="swallow")),
("aid_bitterdrink", "Bitter Drink", RK + "healingpowder.mdl",
 "A tribal brew, bitter enough that you know it is doing something.",
 dict(heal=55, sound=PILL, buffs=[("PER", -2, 120)], healTime=6,
      useEffect="swallow", tint=(120, 90, 50))),
("aid_bloodpack", "Blood Pack", FNV + "bloodpack.mdl",
 "A sealed pack of blood. Not yours, but it will do.",
 dict(heal=20, sound=INJ, healTime=8, useEffect="inject")),
("aid_firstaidkit", "First Aid Kit", FNV + "firstaidkit.mdl",
 "A proper kit. Bandages, sutures, and the time to use them.",
 dict(heal=75, sound=PILL, healTime=10, useEffect="swallow")),
("aid_doctorbag", "Doctor's Bag", FNV + "doctorbag.mdl",
 "Everything a wasteland doctor carries, in one bag.",
 dict(heal=100, sound=PILL, healTime=12, useEffect="swallow")),
("aid_biogel", "Bio Gel", FNV + "biogel.mdl",
 "A cold gel that knits skin back together.",
 dict(heal=50, sound=INJ, healTime=5, useEffect="inject")),
("aid_sludgepak", "Sludgepak", F4 + "sludgepak.mdl",
 "A stimpak brewed in a bathtub. It heals. It also glows.",
 dict(heal=45, radiation=8, sound=INJ, healTime=6, useEffect="inject")),
("aid_hydra", "Hydra", FNV + "chems/hydra.mdl",
 "A thick green syringe. Knits broken limbs back together.",
 dict(heal=65, sound=INJ, addiction="Hydra", chance=15, healTime=8, useEffect="inject")),
("aid_snakebite", "Snakebite Tourniquet", FNV + "snakebitetourniquet.mdl",
 "For when something with fangs got to you first.",
 dict(heal=30, sound=PILL, healTime=6, useEffect="inject")),
("aid_antivenom", "Antivenom", FNV + "antivenom.mdl",
 "Cave fungus and a lot of boiling. Draws the poison out.",
 dict(heal=35, sound=PILL, healTime=5, useEffect="swallow")),

# ---- radiation -------------------------------------------------------------
("aid_radx", "Rad-X", RK + "radx.mdl",
 "Take it before you go in, not after.",
 dict(sound=PILL, aidID="RadX", buffs=[("RADRES", 25, 300)], useEffect="swallow")),
("aid_radxbos", "Rad-X (Brotherhood)", F4 + "radxbos.mdl",
 "Brotherhood issue. The same compound, twice the dose.",
 dict(sound=PILL, aidID="RadX", buffs=[("RADRES", 45, 300)], useEffect="swallow")),
("aid_radaway", "RadAway", RK + "radaway.mdl",
 "An orange drip that flushes radiation out of you. Slowly, and it aches.",
 dict(radiation=-50, sound=RADAWAY, addiction="RadAway", chance=10, useEffect="inject")),
("aid_antresin", "Anti-Resin", FNV + "chems/antresin.mdl",
 "Counteracts the resin. Whatever the resin was.",
 dict(sound=PILL, aidID="AntiResin", buffs=[("RADRES", 30, 240)], useEffect="swallow")),

# ---- combat and stat chems -------------------------------------------------
("aid_jet", "Jet", FNV + "chems/jet.mdl",
 "A brahmin-dung inhaler out of Redding. Everything gets faster.",
 dict(sound=JET, aidID="Jet", buffs=[("SPD", 30, 60)],
      addiction="Jet", chance=25, useEffect="inhale")),
("aid_ultrajet", "Ultrajet", FNV + "chems/jet.mdl",
 "Jet, refined. Faster, longer, and it wants more of you.",
 dict(sound=JET, aidID="Jet", buffs=[("SPD", 45, 90)],
      addiction="Jet", chance=35, useEffect="inhale",
      tint=(120, 190, 235))),
("aid_turbo", "Turbo", FNV + "chems/turbo.mdl",
 "The world slows down. You do not.",
 dict(sound=JET, aidID="Turbo", buffs=[("SPD", 60, 20), ("AGL", 2, 20)],
      addiction="Turbo", chance=30, useEffect="inhale")),
("aid_psycho", "Psycho", FNV + "chems/psycho.mdl",
 "Military issue, discontinued for obvious reasons. You hit much harder.",
 dict(sound=PSYCHO, aidID="Psycho", buffs=[("DMG", 25, 120), ("STR", 2, 120)],
      addiction="Psycho", chance=30, useEffect="inject")),
("aid_slasher", "Slasher", FNV + "chems/psycho.mdl",
 "Psycho cut with Med-X. Hits harder and hurts less.",
 dict(sound=PSYCHO, aidID="Psycho", buffs=[("DMG", 15, 150), ("DR", 10, 150)],
      addiction="Psycho", chance=40, useEffect="inject", tint=(200, 60, 60))),
("aid_buffout", "Buffout", FNV + "chems/buffout.mdl",
 "Bodybuilder pills from before the war. You can take more of a beating.",
 dict(sound=PILL, aidID="Buffout",
      buffs=[("HP", 25, 120), ("STR", 2, 120), ("END", 2, 120)],
      addiction="Buffout", chance=14, timed=True, useEffect="swallow")),
("aid_medx", "Med-X", RK + "medx.mdl",
 "A painkiller strong enough that you stop noticing being shot.",
 dict(sound=MORPHINE, aidID="MedX", buffs=[("DR", 10, 240)],
      addiction="MedX", chance=20, useEffect="inject")),
("aid_mentats", "Mentats", FNV + "chems/mentats.mdl",
 "Sharpens the mind. Wears off sharper still.",
 dict(sound=PILL, aidID="Mentats", buffs=[("INT", 2, 180), ("PER", 2, 180)],
      addiction="Mentats", chance=15, timed=True, useEffect="swallow")),
("aid_berrymentats", "Berry Mentats", FNV + "chems/mentats.mdl",
 "Berry flavoured. Everything is suddenly very clear.",
 dict(sound=PILL, aidID="Mentats", buffs=[("INT", 4, 180)],
      addiction="Mentats", chance=15, timed=True, useEffect="swallow", tint=(150, 60, 190))),
("aid_grapementats", "Grape Mentats", FNV + "chems/mentats.mdl",
 "Grape flavoured. You have never been so persuasive.",
 dict(sound=PILL, aidID="Mentats", buffs=[("CHR", 4, 180)],
      addiction="Mentats", chance=15, timed=True, useEffect="swallow", tint=(90, 70, 200))),
("aid_orangementats", "Orange Mentats", FNV + "chems/mentats.mdl",
 "Orange flavoured. You start noticing things.",
 dict(sound=PILL, aidID="Mentats", buffs=[("PER", 4, 180)],
      addiction="Mentats", chance=15, timed=True, useEffect="swallow", tint=(235, 140, 40))),
("aid_partytimementats", "Party Time Mentats", FNV + "chems/mentats.mdl",
 "The whole tin. You are the most charming person in the room.",
 dict(sound=PILL, aidID="Mentats", buffs=[("CHR", 6, 180), ("INT", -1, 180)],
      addiction="Mentats", chance=25, timed=True, useEffect="swallow", tint=(235, 90, 160))),
("aid_steady", "Steady", FNV + "chems/steady.mdl",
 "Your hands stop shaking entirely.",
 dict(sound=INJ, aidID="Steady", buffs=[("PER", 4, 60)],
      addiction="Steady", chance=10, timed=True, useEffect="inject")),
("aid_rebound", "Rebound", FNV + "chems/rebound.mdl",
 "A stimulant that puts the spring back in your legs.",
 dict(sound=PILL, aidID="Rebound", buffs=[("AGL", 2, 120), ("SPD", 10, 120)],
      addiction="Rebound", chance=15, timed=True, useEffect="swallow")),
("aid_daytripper", "Day Tripper", F4 + "daytripper.mdl",
 "Everything is fine. Everyone likes you.",
 dict(sound=PILL, aidID="DayTripper",
      buffs=[("CHR", 3, 180), ("LCK", 2, 180), ("STR", -1, 180)],
      addiction="DayTripper", chance=20, useEffect="swallow")),
("aid_daddyo", "Daddy-O", F4 + "daddyo.mdl",
 "Beatnik chem. Clears the head and dulls the tongue.",
 dict(sound=PILL, aidID="DaddyO",
      buffs=[("INT", 3, 180), ("PER", 2, 180), ("CHR", -1, 180)],
      addiction="DaddyO", chance=20, useEffect="swallow")),
("aid_cateye", "Cateye", FNV + "chems/cateye.mdl",
 "The dark stops being dark.",
 dict(sound=INJ, aidID="Cateye", buffs=[("PER", 5, 120)],
      addiction="Cateye", chance=10, timed=True, useEffect="inject")),
("aid_xcell", "X-Cell", F4 + "xcell.mdl",
 "Pre-war experimental. Every part of you works better at once.",
 dict(sound=PILL, aidID="XCell",
      buffs=[("STR", 1, 180), ("PER", 1, 180), ("END", 1, 180),
             ("CHR", 1, 180), ("INT", 1, 180), ("AGL", 1, 180),
             ("LCK", 1, 180)],
      addiction="XCell", chance=25, useEffect="swallow")),
("aid_mysteriousserum", "Mysterious Serum", F4 + "mysteriousserum.mdl",
 "Nobody will say where it comes from. It works better than anything else.",
 dict(heal=80, sound=INJ, aidID="Serum",
      buffs=[("DR", 25, 300), ("RADRES", 50, 300)], healTime=6, useEffect="inject")),

# ---- cures and utility -----------------------------------------------------
("aid_fixer", "Fixer", FNV + "chems/fixer.mdl",
 "Clears the chems out of your blood. Unpleasant, and it works.",
 dict(sound=PILL, cures=True, useEffect="swallow")),
("aid_addictol", "Addictol", FNV + "chems/fixer.mdl",
 "An inhaler that does in one breath what Fixer does in an hour.",
 dict(sound=PILL, cures=True, useEffect="inhale", tint=(90, 200, 230))),
("aid_stealthboy", "Stealth Boy", FNV + "chems/stealthboy.mdl",
 "A wrist-mounted stealth field. Fragile, and the batteries do not last.",
 dict(sound=STEALTHBOY, aidID="StealthBoy", buffs=[("STEALTH", 1, 90)],
      useEffect="inject")),
("aid_robotrepair", "Robot Repair Kit", F4 + "robotrepair.mdl",
 "Patches plating and reseats servos. Of no use to anything with blood.",
 dict(heal=70, sound=PILL, healTime=8, useEffect="swallow", mechanical=True)),
]

# Withdrawal: what each addiction does at severity 1, 2 and 3.
# Applied cumulatively, so three -15 steps read as -15 / -30 / -45.
ADDICTIONS = {
    "Jet": dict(label="Jet", interval=120, timed=False,
                effects={1: [("SPD", -15)], 2: [("SPD", -15)], 3: [("SPD", -15)]},
                screen={2: ["sobel"], 3: ["sobel", "blur"]},
                  messages={1: "You feel sluggish.", 2: "You feel fatigued.",
                          3: "You are in severe withdrawal."}),
    "Turbo": dict(label="Turbo", interval=120, timed=False,
                  effects={1: [("AGL", -1)], 2: [("AGL", -1), ("SPD", -15)],
                           3: [("AGL", -1), ("SPD", -20)]},
                  screen={2: ["blur"], 3: ["blur", "sobel"]},
                  messages={1: "Your reactions are dulling.",
                            2: "Your hands are shaking.",
                            3: "You can barely hold still."}),
    "Psycho": dict(label="Psycho", interval=120, timed=False,
                   effects={1: [("DMG", -10)], 2: [("DMG", -10), ("STR", -1)],
                            3: [("DMG", -10), ("STR", -2)]},
                   screen={2: ["grey"], 3: ["grey", "sobel"]},
                  messages={1: "Your temper is fraying.",
                             2: "You feel weak and angry.",
                             3: "You cannot think through the rage."}),
    "Buffout": dict(label="Buffout", interval=120, timed=True,
                    effects={1: [("HP", -10)], 2: [("HP", -10), ("END", -1)],
                             3: [("HP", -15), ("END", -2)]},
                    screen={2: ["grey"], 3: ["grey", "blur"]},
                  messages={1: "You feel hollow.", 2: "Your chest aches.",
                              3: "You can hardly stand."}),
    "MedX": dict(label="Med-X", interval=120, timed=False,
                 effects={1: [("DR", -5)], 2: [("DR", -5), ("END", -1)],
                          3: [("DR", -10), ("END", -1)]},
                 screen={2: ["nausea"], 3: ["nausea", "blur"]},
                  messages={1: "Everything is starting to hurt.",
                           2: "The pain is getting hard to ignore.",
                           3: "Every step is agony."}),
    "Mentats": dict(label="Mentats", interval=120, timed=True,
                    effects={1: [("INT", -1)], 2: [("INT", -1), ("PER", -1)],
                             3: [("INT", -2), ("PER", -1)]},
                    screen={2: ["sobel"], 3: ["sobel", "toytown"]},
                  messages={1: "Your thoughts are getting slow.",
                              2: "You keep losing the thread.",
                              3: "You cannot hold an idea in your head."}),
    "Steady": dict(label="Steady", interval=120, timed=True,
                   effects={1: [("PER", -1)], 2: [("PER", -2)], 3: [("PER", -2)]},
                   screen={2: ["blur"], 3: ["blur", "sobel"]},
                  messages={1: "Your aim is drifting.",
                             2: "You cannot keep the sights still.",
                             3: "Your hands will not stop shaking."}),
    "Rebound": dict(label="Rebound", interval=120, timed=True,
                    effects={1: [("AGL", -1)], 2: [("AGL", -1), ("SPD", -10)],
                             3: [("AGL", -2), ("SPD", -10)]},
                    screen={2: ["grey"], 3: ["grey", "blur"]},
                  messages={1: "You feel heavy.", 2: "Your legs are lead.",
                              3: "You can barely lift your feet."}),
    "DayTripper": dict(label="Day Tripper", interval=120, timed=False,
                       effects={1: [("CHR", -1)], 2: [("CHR", -2), ("LCK", -1)],
                                3: [("CHR", -2), ("LCK", -2)]},
                       screen={2: ["grey"], 3: ["grey", "sobel"]},
                  messages={1: "The world is greyer than it was.",
                                 2: "Nothing seems worth saying.",
                                 3: "You cannot look anyone in the eye."}),
    "DaddyO": dict(label="Daddy-O", interval=120, timed=False,
                   effects={1: [("INT", -1)], 2: [("INT", -2)],
                            3: [("INT", -2), ("PER", -1)]},
                   screen={2: ["grey"], 3: ["grey", "blur"]},
                  messages={1: "Your head is fogging up.",
                             2: "You keep forgetting things.",
                             3: "You cannot follow what anyone is saying."}),
    "Cateye": dict(label="Cateye", interval=120, timed=True,
                   effects={1: [("PER", -1)], 2: [("PER", -2)], 3: [("PER", -3)]},
                   screen={2: ["sharpen"], 3: ["sharpen", "sobel"]},
                  messages={1: "Your eyes are aching.",
                             2: "The light hurts.",
                             3: "You can hardly see straight."}),
    "XCell": dict(label="X-Cell", interval=120, timed=False,
                  effects={1: [("STR", -1), ("END", -1)],
                           2: [("PER", -1), ("AGL", -1)],
                           3: [("INT", -1), ("LCK", -1), ("HP", -10)]},
                  screen={2: ["nausea"], 3: ["nausea", "sobel", "blur"]},
                  messages={1: "Every part of you is complaining.",
                            2: "You feel wrung out.",
                            3: "Your whole body is failing you."}),
    "Hydra": dict(label="Hydra", interval=120, timed=True,
                  effects={1: [("END", -1)], 2: [("END", -2)],
                           3: [("END", -2), ("HP", -15)]},
                  screen={2: ["nausea"], 3: ["nausea", "grey"]},
                  messages={1: "Your old wounds are aching.",
                            2: "Everything that was broken hurts again.",
                            3: "You feel like you are coming apart."}),
    "RadAway": dict(label="RadAway", interval=120, timed=True,
                    effects={1: [("END", -1)], 2: [("END", -1), ("HP", -10)],
                             3: [("END", -2), ("HP", -15)]},
                    screen={2: ["nausea"], 3: ["nausea", "blur"]},
                  messages={1: "You feel washed out.",
                              2: "Your veins are burning.",
                              3: "You cannot keep anything down."}),
}

# ---- variants and the rest of the roster -----------------------------------
# Where two chems share a model, `tint` puts a coloured marker on the icon so
# they can be told apart in an inventory - Psycho-Jet and Psycho are the same
# syringe otherwise.
CHEMS += [
("aid_psychojet", "Psycho-Jet", FNV + "chems/psycho.mdl",
 "Psycho and Jet in one syringe. Faster and angrier at the same time.",
 dict(sound=PSYCHO, aidID="PsychoJet", useEffect="inject", tint=(230, 120, 40),
      buffs=[("DMG", 20, 90), ("SPD", 25, 90)],
      addiction="PsychoJet", chance=45)),
("aid_buffjet", "Buffjet", FNV + "chems/jet.mdl",
 "Buffout cut into a Jet inhaler. Tougher and quicker.",
 dict(sound=JET, aidID="Buffjet", useEffect="inhale", tint=(120, 200, 120),
      buffs=[("HP", 20, 90), ("SPD", 25, 90)],
      addiction="Buffjet", chance=40)),
("aid_bufftats", "Bufftats", FNV + "chems/buffout.mdl",
 "Buffout and Mentats pressed together. Stronger and sharper.",
 dict(sound=PILL, aidID="Bufftats", useEffect="swallow", tint=(120, 140, 220),
      buffs=[("HP", 20, 150), ("STR", 2, 150), ("INT", 2, 150)],
      addiction="Bufftats", chance=35)),
("aid_psychobuff", "Psychobuff", FNV + "chems/psycho.mdl",
 "Psycho and Buffout. Everything hurts less and hits harder.",
 dict(sound=PSYCHO, aidID="Psychobuff", useEffect="inject", tint=(200, 130, 60),
      buffs=[("DMG", 20, 150), ("HP", 20, 150), ("STR", 2, 150)],
      addiction="Psychobuff", chance=45)),
("aid_psychotats", "Psychotats", FNV + "chems/psycho.mdl",
 "Psycho and Mentats. Sharp, and looking for a fight.",
 dict(sound=PSYCHO, aidID="Psychotats", useEffect="inject", tint=(180, 80, 200),
      buffs=[("DMG", 20, 150), ("PER", 3, 150)],
      addiction="Psychotats", chance=40)),
("aid_jetfuel", "Jet Fuel", FNV + "chems/jet.mdl",
 "Jet cut with turpentine. It burns going in.",
 dict(sound=JET, aidID="Jet", useEffect="inhale", tint=(230, 200, 60),
      buffs=[("SPD", 55, 45)], addiction="Jet", chance=45)),
("aid_rocket", "Rocket", FNV + "chems/jet.mdl",
 "Nuka-Cola and Jet. Crude, and it moves.",
 dict(sound=JET, aidID="Jet", useEffect="inhale", tint=(200, 60, 90),
      buffs=[("SPD", 40, 60), ("AGL", 1, 60)],
      addiction="Jet", chance=30)),
("aid_overdrive", "Overdrive", FNV + "chems/psycho.mdl",
 "You start landing hits you had no business landing.",
 dict(sound=PSYCHO, aidID="Overdrive", useEffect="inject", tint=(240, 190, 70),
      buffs=[("DMG", 15, 180), ("LCK", 2, 180)],
      addiction="Overdrive", chance=25)),
("aid_fury", "Fury", FNV + "chems/psycho.mdl",
 "Super mutant chem. Enormous strength and no judgement at all.",
 dict(sound=PSYCHO, aidID="Fury", useEffect="inject", tint=(150, 40, 40),
      buffs=[("DMG", 40, 90), ("STR", 4, 90), ("INT", -3, 90)],
      addiction="Fury", chance=55)),
("aid_calmex", "Calmex", FNV + "chems/mentats.mdl",
 "A sedative from the Sierra Madre. Steady hands, soft footsteps.",
 dict(sound=PILL, aidID="Calmex", useEffect="swallow", tint=(80, 190, 190),
      buffs=[("PER", 3, 180), ("DMG", 10, 180)],
      addiction="Calmex", chance=20)),
("aid_coyote", "Coyote Tobacco Chew", RK + "healingpowder.mdl",
 "A tribal chew. Steadies you and dulls the edges.",
 dict(sound=PILL, aidID="Coyote", useEffect="swallow", tint=(150, 110, 60),
      buffs=[("PER", 2, 240), ("INT", -1, 240)],
      addiction="Coyote", chance=15)),
("aid_datura", "Datura Hide", RK + "healingpowder.mdl",
 "Ground datura root. Numbs everything, including the parts you need.",
 dict(sound=PILL, aidID="Datura", useEffect="swallow", tint=(120, 80, 160),
      buffs=[("DR", 8, 180), ("PER", -2, 180)],
      addiction="Datura", chance=20)),
("aid_antnectar", "Ant Nectar", FNV + "chems/jet.mdl",
 "Thick and sweet, straight from the nest. Enormously strong for a while.",
 dict(sound=PILL, aidID="AntNectar", useEffect="swallow", tint=(220, 170, 50),
      buffs=[("STR", 4, 120), ("PER", -2, 120)],
      addiction="AntNectar", chance=30)),
("aid_turpentine", "Turpentine", RK + "healingpowder.mdl",
 "Not meant to be drunk. People drink it anyway.",
 dict(sound=PILL, useEffect="swallow", tint=(200, 200, 120), radiation=5,
      buffs=[("STR", 2, 120), ("INT", -2, 120), ("PER", -2, 120)],
      addiction="Turpentine", chance=35)),
("aid_medx_auto", "Auto-Inject Med-X", RK + "medx.mdl",
 "Med-X with a pressure trigger. Goes through armour.",
 dict(sound=MORPHINE, aidID="MedX", useEffect="inject", tint=(90, 160, 230),
      buffs=[("DR", 12, 240)], addiction="MedX", chance=20)),
("aid_superstimpak_auto", "Auto-Inject Super Stimpak",
 FNV + "superstimpak_auto.mdl",
 "A super stimpak that fires itself. Goes through most things.",
 dict(heal=100, healTime=4, sound=INJ, useEffect="inject",
      buffs=[("END", -1, 60)])),
("aid_stimpak_diluted", "Diluted Stimpak", FNV + "stimpak_clean.mdl",
 "Stretched with clean water. Half as good, twice as many.",
 dict(heal=20, healTime=4, sound=INJ, useEffect="inject", tint=(160, 200, 220))),
("aid_radaway_diluted", "Diluted RadAway", RK + "radaway.mdl",
 "Cut with water. Gentler, and it takes less out.",
 dict(radiation=-25, sound=RADAWAY, useEffect="inject", tint=(160, 200, 220),
      addiction="RadAway", chance=5)),
("aid_radshield", "Rad Shield", RK + "radx.mdl",
 "A stronger Rad-X. Brotherhood chemists, mostly.",
 dict(sound=PILL, aidID="RadX", useEffect="inject", tint=(120, 220, 140),
      buffs=[("RADRES", 60, 240)])),
("aid_stimpak_diffuser", "Stimpak Diffuser", F4 + "ivbag.mdl",
 "A canister that heals everyone standing near it. Yourself included.",
 dict(heal=60, healTime=8, sound=INJ, useEffect="inhale")),
("aid_berserk", "Berserk", FNV + "chems/psycho.mdl",
 "Raider chem. You will not feel a thing, and you will not stop.",
 dict(sound=PSYCHO, aidID="Berserk", useEffect="inject", tint=(90, 30, 30),
      buffs=[("DMG", 35, 60), ("DR", -10, 60), ("STR", 3, 60)],
      addiction="Berserk", chance=50)),
("aid_cloudkiss", "Cloud Kiss", FNV + "cloudkiss.mdl",
 "Distilled from the Cloud. It should not be breathable and it is.",
 dict(sound=PILL, aidID="CloudKiss", useEffect="inhale", radiation=10,
      buffs=[("PER", 3, 150), ("END", 2, 150)],
      addiction="CloudKiss", chance=35)),
("aid_alienepoxy", "Alien Epoxy", FNV + "alienepoxy.mdl",
 "Zetan. It seals a wound shut in seconds and nobody knows how.",
 dict(heal=90, healTime=3, sound=INJ, useEffect="inject")),
("aid_repairkit", "Repair Kit", FNV + "repairkit.mdl",
 "Tools and patches. For armour, and at a push for people.",
 dict(heal=40, healTime=10, sound=PILL, useEffect="swallow",
      mechanical=True)),
]

ADDICTIONS.update({
    "PsychoJet": dict(label="Psycho-Jet", interval=120, timed=False,
        effects={1: [("SPD", -15), ("DMG", -10)],
                 2: [("SPD", -15), ("DMG", -10)],
                 3: [("SPD", -15), ("DMG", -10)]},
        messages={1: "You are coming down hard.",
                  2: "Everything is slow and pointless.",
                  3: "You can barely move for wanting more."},
        screen={2: ["sobel", "grey"], 3: ["sobel", "grey", "blur"]}),
    "Buffjet": dict(label="Buffjet", interval=120, timed=False,
        effects={1: [("SPD", -15)], 2: [("SPD", -15), ("HP", -10)],
                 3: [("SPD", -15), ("HP", -15)]},
        messages={1: "You feel sluggish.", 2: "You feel hollow and slow.",
                  3: "You can hardly stand up straight."},
        screen={2: ["sobel"], 3: ["sobel", "blur"]}),
    "Bufftats": dict(label="Bufftats", interval=120, timed=True,
        effects={1: [("INT", -1)], 2: [("INT", -1), ("HP", -10)],
                 3: [("INT", -2), ("HP", -15)]},
        messages={1: "Your head is thick.", 2: "You feel weak and stupid.",
                  3: "Nothing is working properly."},
        screen={2: ["sobel"], 3: ["sobel", "grey"]}),
    "Psychobuff": dict(label="Psychobuff", interval=120, timed=False,
        effects={1: [("DMG", -10)], 2: [("DMG", -10), ("HP", -10)],
                 3: [("DMG", -10), ("HP", -15), ("STR", -2)]},
        messages={1: "Your temper is fraying.", 2: "You feel weak and furious.",
                  3: "You are shaking with it."},
        screen={2: ["grey"], 3: ["grey", "sobel"]}),
    "Psychotats": dict(label="Psychotats", interval=120, timed=False,
        effects={1: [("PER", -1)], 2: [("PER", -2), ("DMG", -10)],
                 3: [("PER", -3), ("DMG", -10)]},
        messages={1: "The edges are going soft.",
                  2: "You cannot focus on anything.",
                  3: "Everything is noise."},
        screen={2: ["sobel"], 3: ["sobel", "toytown"]}),
    "Overdrive": dict(label="Overdrive", interval=120, timed=True,
        effects={1: [("LCK", -1)], 2: [("LCK", -2), ("DMG", -10)],
                 3: [("LCK", -2), ("DMG", -15)]},
        messages={1: "Nothing is going your way.",
                  2: "You keep missing.", 3: "You cannot hit anything."},
        screen={2: ["grey"], 3: ["grey", "blur"]}),
    "Fury": dict(label="Fury", interval=120, timed=False,
        effects={1: [("STR", -2), ("DMG", -15)],
                 2: [("STR", -2), ("DMG", -15)],
                 3: [("STR", -2), ("DMG", -15), ("HP", -20)]},
        messages={1: "The rage is draining out of you.",
                  2: "You feel small and slow.",
                  3: "You are barely holding together."},
        screen={2: ["grey", "sobel"], 3: ["grey", "sobel", "blur"]}),
    "Calmex": dict(label="Calmex", interval=120, timed=True,
        effects={1: [("PER", -1)], 2: [("PER", -2)],
                 3: [("PER", -3), ("DMG", -10)]},
        messages={1: "You are jumpy.", 2: "You cannot settle.",
                  3: "Every noise makes you flinch."},
        screen={2: ["sharpen"], 3: ["sharpen", "blur"]}),
    "Coyote": dict(label="Coyote Tobacco", interval=120, timed=True,
        effects={1: [("PER", -1)], 2: [("PER", -1), ("END", -1)],
                 3: [("PER", -2), ("END", -1)]},
        messages={1: "You want a chew.", 2: "You cannot think past wanting one.",
                  3: "Your hands will not keep still."},
        screen={2: ["grey"], 3: ["grey", "sobel"]}),
    "Datura": dict(label="Datura", interval=120, timed=False,
        effects={1: [("PER", -1)], 2: [("PER", -2), ("DR", -5)],
                 3: [("PER", -3), ("DR", -10)]},
        messages={1: "The colours are wrong.",
                  2: "Things are moving that should not be.",
                  3: "You cannot tell what is real."},
        screen={2: ["toytown"], 3: ["toytown", "blur", "nausea"]}),
    "AntNectar": dict(label="Ant Nectar", interval=120, timed=False,
        effects={1: [("STR", -2)], 2: [("STR", -3), ("PER", -1)],
                 3: [("STR", -4), ("PER", -2)]},
        messages={1: "You feel wrung out.", 2: "You have no strength at all.",
                  3: "You can barely lift your arms."},
        screen={2: ["grey"], 3: ["grey", "nausea"]}),
    "Turpentine": dict(label="Turpentine", interval=120, timed=True,
        effects={1: [("INT", -1), ("PER", -1)],
                 2: [("INT", -2), ("PER", -1)],
                 3: [("INT", -2), ("PER", -2), ("HP", -10)]},
        messages={1: "Your head is splitting.", 2: "You cannot see straight.",
                  3: "You are poisoning yourself and you know it."},
        screen={2: ["nausea"], 3: ["nausea", "blur", "sobel"]}),
    "Berserk": dict(label="Berserk", interval=120, timed=False,
        effects={1: [("DMG", -15), ("STR", -2)],
                 2: [("DMG", -15), ("STR", -2)],
                 3: [("DMG", -15), ("STR", -2), ("HP", -20)]},
        messages={1: "The edge is gone.", 2: "You feel wrong without it.",
                  3: "You would do almost anything for more."},
        screen={2: ["rage", "sobel"], 3: ["rage", "sobel", "blur"]}),
    "CloudKiss": dict(label="Cloud Kiss", interval=120, timed=False,
        effects={1: [("END", -1)], 2: [("END", -2), ("PER", -1)],
                 3: [("END", -2), ("PER", -2), ("HP", -10)]},
        messages={1: "Your chest is tight.", 2: "You cannot get a full breath.",
                  3: "Every breath burns."},
        screen={2: ["nausea"], 3: ["nausea", "grey", "blur"]}),
})
