"""
Regenerate the race injector items from the race roster.

Two items per race - one permanent, one temporary - written into
schema/items/injector/. Run it again after adding a race:

    python _docs/tools/geninjectors.py

Every file it writes is generated; nothing hand-written lives in that folder,
and the script refuses to touch anything it did not write (it checks for the
marker line at the top).

NAMING. "Injector" only makes sense for something you can put in a syringe, so:

  * robots get a CONVERSION KIT - you are not injected into being a Securitron,
    you are rebuilt as one
  * the human item is an ANTI-MUTAGEN SERUM, because turning back into a human
    is a cure rather than a dose
  * everything else is an injector, permanent, or an "unstable" one for the
    temporary version - which is also the flavour: it does not hold

See schema/libs/sh_raceinject.lua for what the items actually do.
"""

import io
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SCHEMA = os.path.join(ROOT, "garrysmod", "gamemodes", "falloutrp", "schema")
RACES = os.path.join(SCHEMA, "races")
OUT = os.path.join(SCHEMA, "items", "injector")

MARKER = "-- Generated by _docs/tools/geninjectors.py - do not edit by hand."

# Races that are machines. A kit rather than a needle.
ROBOTS = {
    "eyebot", "libertyprime", "mistergutsy", "protectron", "robobrain",
    "roboscorpion", "securitron", "securitronexecutive", "sentrybot",
}

# The model each kind of item uses. Checked with resolve_asset.py.
#
# The syringe is Phoenix's own injector prop rather than the stimpak model the
# first version used - a race injector that looks exactly like a stimpak is a
# race injector somebody uses by accident, and that one cannot be undone.
SYRINGE = "models/mosi/fallout4/props/junk/injector.mdl"
KIT = "models/mosi/fallout4/props/junk/modbox.mdl"


def read_races():
    """(class, name) for every race file, in roster order."""
    out = []

    for name in sorted(os.listdir(RACES)):
        if not name.startswith("sh_") or not name.endswith(".lua"):
            continue

        text = io.open(os.path.join(RACES, name), encoding="utf-8").read()
        klass = re.search(r'RACE\.class\s*=\s*"([^"]+)"', text)
        title = re.search(r'RACE\.name\s*=\s*"([^"]+)"', text)

        if not klass:
            continue

        out.append((klass.group(1), title.group(1) if title else klass.group(1)))

    return out


def names(klass, title, temporary):
    """The item name and the flavour line for one race and kind."""
    if klass == "human":
        if temporary:
            return ("Unstable Anti-Mutagen Serum",
                    "A thin serum that argues your cells back into the shape "
                    "they were born in. The argument does not hold.")

        return ("Anti-Mutagen Serum",
                "A thin serum that argues your cells back into the shape they "
                "were born in, and wins.")

    if klass in ROBOTS:
        if temporary:
            return ("Temporary %s Conversion Kit" % title,
                    "A field rig that drives a body through a %s chassis "
                    "pattern. The frame gives out and lets you go." % title)

        return ("%s Conversion Kit" % title,
                "A field rig that rebuilds a body into a %s. There is no "
                "reversing the wiring afterwards." % title)

    if temporary:
        return ("Unstable %s Injector" % title,
                "A dose of unfixed %s genetic material. It takes, and then it "
                "lets go." % title.lower())

    return ("%s Injector" % title,
            "A dose of stabilised %s genetic material. What it does to you, "
            "it keeps." % title.lower())


TEMPLATE = """%s

ITEM.name = "%s"
ITEM.description = "%s"
ITEM.model = "%s"

ITEM.race = "%s"
ITEM.temporary = %s
"""


def wrap(text, width=58):
    """Lua string concatenation, wrapped to fit inside eighty columns."""
    words = text.split()
    lines, current = [], ""

    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = (current + " " + word).strip()

    lines.append(current)

    if len(lines) == 1:
        return '"%s"' % lines[0]

    out = ['"%s "' % lines[0]]

    for index, line in enumerate(lines[1:]):
        last = index == len(lines) - 2
        out.append('\t.. "%s%s"' % (line, "" if last else " "))

    return "\n".join(out)


def main():
    if not os.path.isdir(OUT):
        os.makedirs(OUT)

    # Anything generated before is removed first, so a race that has been
    # deleted does not leave its injectors behind for ever.
    for name in os.listdir(OUT):
        path = os.path.join(OUT, name)
        head = io.open(path, encoding="utf-8").readline().strip()

        if head == MARKER:
            os.remove(path)
        else:
            print("  left alone (not generated): %s" % name)

    written = 0

    for klass, title in read_races():
        for temporary in (False, True):
            name, description = names(klass, title, temporary)
            model = KIT if klass in ROBOTS else SYRINGE
            uniqueID = "injector_%s%s" % (klass, "_temp" if temporary else "")

            body = TEMPLATE % (MARKER, name, "@DESC@", model, klass,
                               "true" if temporary else "false")
            body = body.replace('"@DESC@"', wrap(description))

            io.open(os.path.join(OUT, "sh_%s.lua" % uniqueID), "w",
                    encoding="utf-8", newline="\n").write(body)

            written += 1

    print("wrote %d injector item(s) into %s" % (written, OUT))


if __name__ == "__main__":
    main()
