--[[
	Default blueprint recipes.

	GENERATED FILE. The roster is read from the installed weapons by
	`_docs/tools/blueprints.py`; run `_docs/tools/genblueprints.py`.
]]

ix.blueprint = ix.blueprint or {}

--- `[weapon] = {input = {{item, amount}, ...}, time, xp}`.
ix.blueprint.defaults = {
	["32_pistol"] = {time = 70, xp = 18, input = {{"frame_32_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["45_auto_smg"] = {time = 90, xp = 22, input = {{"frame_45_auto_smg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["50_smg"] = {time = 90, xp = 22, input = {{"frame_50_smg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["alien_atomizer"] = {time = 90, xp = 22, input = {{"frame_alien_atomizer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["asval"] = {time = 90, xp = 22, input = {{"frame_asval", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["aug"] = {time = 90, xp = 22, input = {{"frame_aug", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["bellumbanner"] = {time = 70, xp = 18, input = {{"frame_bellumbanner", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["caws"] = {time = 90, xp = 22, input = {{"frame_caws", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["cit_laser"] = {time = 90, xp = 22, input = {{"frame_cit_laser", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["cit_v3n_biorifle"] = {time = 90, xp = 22, input = {{"frame_cit_v3n_biorifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["colt357"] = {time = 70, xp = 18, input = {{"frame_colt357", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["cryolator"] = {time = 90, xp = 22, input = {{"frame_cryolator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["detonator"] = {time = 50, xp = 14, input = {{"frame_detonator", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}}},
	["drone_cannon"] = {time = 90, xp = 22, input = {{"frame_drone_cannon", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["equipment_artillery_finder"] = {time = 50, xp = 14, input = {{"frame_equipment_artillery_finder", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}}},
	["equipment_binoculars"] = {time = 90, xp = 22, input = {{"frame_equipment_binoculars", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}}},
	["equipment_laser_designator"] = {time = 50, xp = 14, input = {{"frame_equipment_laser_designator", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["equipment_radscanner"] = {time = 70, xp = 18, input = {{"frame_equipment_radscanner", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}}},
	["flare_gun"] = {time = 70, xp = 18, input = {{"frame_flare_gun", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["g11"] = {time = 90, xp = 22, input = {{"frame_g11", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_cryo"] = {time = 90, xp = 22, input = {{"frame_grenade_cryo", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_dynamite"] = {time = 90, xp = 22, input = {{"frame_grenade_dynamite", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_flash"] = {time = 90, xp = 22, input = {{"frame_grenade_flash", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_frag"] = {time = 90, xp = 22, input = {{"frame_grenade_frag", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_holy"] = {time = 90, xp = 22, input = {{"frame_grenade_holy", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_incin"] = {time = 90, xp = 22, input = {{"frame_grenade_incin", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_plasma"] = {time = 90, xp = 22, input = {{"frame_grenade_plasma", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["grenade_pulse"] = {time = 90, xp = 22, input = {{"frame_grenade_pulse", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["grenade_smoke"] = {time = 90, xp = 22, input = {{"frame_grenade_smoke", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["gyrojet"] = {time = 90, xp = 22, input = {{"frame_gyrojet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["infiltrator"] = {time = 90, xp = 22, input = {{"frame_infiltrator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["jackhammer"] = {time = 90, xp = 22, input = {{"frame_jackhammer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["laser_detonator"] = {time = 50, xp = 14, input = {{"frame_laser_detonator", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["m107a1"] = {time = 90, xp = 22, input = {{"frame_m107a1", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["meleearts_blade_bumpersword"] = {time = 110, xp = 26, input = {{"frame_meleearts_blade_bumpersword", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_chainsaw"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_chainsaw", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_chineseofficer"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_chineseofficer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_cleaver"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_cleaver", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_combatknife"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_combatknife", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_fireaxe"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_fireaxe", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_hatchet"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_hatchet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_kitchenknife"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_kitchenknife", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_laserkatana"] = {time = 110, xp = 26, input = {{"frame_meleearts_blade_laserkatana", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_machete"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_machete", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_machetegladius"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_machetegladius", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_pickaxe"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_pickaxe", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_shishkebab"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_shishkebab", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_straightrazor"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_straightrazor", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blade_switchblade"] = {time = 90, xp = 22, input = {{"frame_meleearts_blade_switchblade", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blund_policebaton"] = {time = 90, xp = 22, input = {{"frame_meleearts_blund_policebaton", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_9iron"] = {time = 110, xp = 26, input = {{"frame_meleearts_blunt_9iron", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_baseballbat"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_baseballbat", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_boomstick"] = {time = 110, xp = 26, input = {{"frame_meleearts_blunt_boomstick", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_cattleprod"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_cattleprod", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_dresscane"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_dresscane", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_leadpipe"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_leadpipe", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_nailboard"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_nailboard", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_poolcue"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_poolcue", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_rebarclub"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_rebarclub", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_rollingpin"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_rollingpin", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_sledgehammer"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_sledgehammer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_supersledge"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_supersledge", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_blunt_tireiron"] = {time = 90, xp = 22, input = {{"frame_meleearts_blunt_tireiron", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_classic_supersledge"] = {time = 90, xp = 22, input = {{"frame_meleearts_classic_supersledge", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_spear_tribalspear"] = {time = 90, xp = 22, input = {{"frame_meleearts_spear_tribalspear", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_ballisticfist"] = {time = 70, xp = 18, input = {{"frame_meleearts_unarmed_ballisticfist", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_bladedgauntlet"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_bladedgauntlet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_boxinggloves"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_boxinggloves", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_brassknuckles"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_brassknuckles", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_deathclawgauntlet"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_deathclawgauntlet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_mantisgauntlet"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_mantisgauntlet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_powerfist"] = {time = 70, xp = 18, input = {{"frame_meleearts_unarmed_powerfist", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_spikedknuckles"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_spikedknuckles", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_yaoguaigauntlet"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_yaoguaigauntlet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["meleearts_unarmed_zapglove"] = {time = 90, xp = 22, input = {{"frame_meleearts_unarmed_zapglove", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_wood", 2}, {"mat_duct_tape", 1}}},
	["mine_bottlecap"] = {time = 90, xp = 22, input = {{"frame_mine_bottlecap", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mine_c4"] = {time = 90, xp = 22, input = {{"frame_mine_c4", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mine_cryo"] = {time = 90, xp = 22, input = {{"frame_mine_cryo", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mine_frag"] = {time = 90, xp = 22, input = {{"frame_mine_frag", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mine_plasma"] = {time = 90, xp = 22, input = {{"frame_mine_plasma", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["mine_pulse"] = {time = 90, xp = 22, input = {{"frame_mine_pulse", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mod_sniper"] = {time = 90, xp = 22, input = {{"frame_mod_sniper", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["mp5"] = {time = 90, xp = 22, input = {{"frame_mp5", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["plasma_glock"] = {time = 90, xp = 22, input = {{"frame_plasma_glock", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["railway_rifle"] = {time = 90, xp = 22, input = {{"frame_railway_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["shoulder_mounted_machine_gun"] = {time = 90, xp = 22, input = {{"frame_shoulder_mounted_machine_gun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["smmg"] = {time = 90, xp = 22, input = {{"frame_smmg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["sonic_emitter"] = {time = 90, xp = 22, input = {{"frame_sonic_emitter", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["spas"] = {time = 90, xp = 22, input = {{"frame_spas", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["storm_drum"] = {time = 90, xp = 22, input = {{"frame_storm_drum", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["sup_sniper"] = {time = 90, xp = 22, input = {{"frame_sup_sniper", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["syringe_pistol"] = {time = 70, xp = 18, input = {{"frame_syringe_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["tesla_rifle"] = {time = 90, xp = 22, input = {{"frame_tesla_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["thorwable_spear"] = {time = 90, xp = 22, input = {{"frame_thorwable_spear", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_abilene"] = {time = 90, xp = 22, input = {{"frame_unique_abilene", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_aer14prototype"] = {time = 90, xp = 22, input = {{"frame_unique_aer14prototype", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_alienblaster"] = {time = 90, xp = 22, input = {{"frame_unique_alienblaster", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_allamerican"] = {time = 90, xp = 22, input = {{"frame_unique_allamerican", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_annabelle"] = {time = 90, xp = 22, input = {{"frame_unique_annabelle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_bigboomer"] = {time = 90, xp = 22, input = {{"frame_unique_bigboomer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_bozar"] = {time = 90, xp = 22, input = {{"frame_unique_bozar", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_christinecos"] = {time = 90, xp = 22, input = {{"frame_unique_christinecos", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_cleansingflame"] = {time = 90, xp = 22, input = {{"frame_unique_cleansingflame", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_complianceregulator"] = {time = 90, xp = 22, input = {{"frame_unique_complianceregulator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_cz57avenger"] = {time = 90, xp = 22, input = {{"frame_unique_cz57avenger", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_dinnerbell"] = {time = 90, xp = 22, input = {{"frame_unique_dinnerbell", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_elijahsadvancedlaer"] = {time = 90, xp = 22, input = {{"frame_unique_elijahsadvancedlaer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_elijasjurryriggedteslacannon"] = {time = 90, xp = 22, input = {{"frame_unique_elijasjurryriggedteslacannon", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_esther"] = {time = 90, xp = 22, input = {{"frame_unique_esther", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_euclidcfinder"] = {time = 90, xp = 22, input = {{"frame_unique_euclidcfinder", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_fido"] = {time = 90, xp = 22, input = {{"frame_unique_fido", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_greatbeargrenaderifle"] = {time = 90, xp = 22, input = {{"frame_unique_greatbeargrenaderifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_holorifle"] = {time = 90, xp = 22, input = {{"frame_unique_holorifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_holyfraggrenade"] = {time = 90, xp = 22, input = {{"frame_unique_holyfraggrenade", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_lalonguecarabine"] = {time = 90, xp = 22, input = {{"frame_unique_lalonguecarabine", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_lightinshiningdarkness"] = {time = 70, xp = 18, input = {{"frame_unique_lightinshiningdarkness", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["unique_lildevil"] = {time = 90, xp = 22, input = {{"frame_unique_lildevil", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_lucky"] = {time = 70, xp = 18, input = {{"frame_unique_lucky", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["unique_maria"] = {time = 90, xp = 22, input = {{"frame_unique_maria", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_medicinestick"] = {time = 90, xp = 22, input = {{"frame_unique_medicinestick", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_mercenarysgrenaderifle"] = {time = 90, xp = 22, input = {{"frame_unique_mercenarysgrenaderifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_mercy"] = {time = 90, xp = 22, input = {{"frame_unique_mercy", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_mfhyperbreederalpha"] = {time = 90, xp = 22, input = {{"frame_unique_mfhyperbreederalpha", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_mysteriousmagnum"] = {time = 90, xp = 22, input = {{"frame_unique_mysteriousmagnum", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_paciencia"] = {time = 90, xp = 22, input = {{"frame_unique_paciencia", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_pewpew"] = {time = 90, xp = 22, input = {{"frame_unique_pewpew", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_pulsegun"] = {time = 90, xp = 22, input = {{"frame_unique_pulsegun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_q35mattermodulator"] = {time = 90, xp = 22, input = {{"frame_unique_q35mattermodulator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_ratslayer"] = {time = 90, xp = 22, input = {{"frame_unique_ratslayer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_redglare"] = {time = 90, xp = 22, input = {{"frame_unique_redglare", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_redvictorygrenaderifle"] = {time = 90, xp = 22, input = {{"frame_unique_redvictorygrenaderifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_sleepytyme"] = {time = 90, xp = 22, input = {{"frame_unique_sleepytyme", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_sprtelwood"] = {time = 90, xp = 22, input = {{"frame_unique_sprtelwood", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_sturdycaravanshotgun"] = {time = 90, xp = 22, input = {{"frame_unique_sturdycaravanshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_survivalistsrifle"] = {time = 90, xp = 22, input = {{"frame_unique_survivalistsrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_teslabeatonprototype"] = {time = 90, xp = 22, input = {{"frame_unique_teslabeatonprototype", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_thatgun"] = {time = 90, xp = 22, input = {{"frame_unique_thatgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_thesmittyspecial"] = {time = 90, xp = 22, input = {{"frame_unique_thesmittyspecial", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_thismachine"] = {time = 90, xp = 22, input = {{"frame_unique_thismachine", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_thumpthump"] = {time = 90, xp = 22, input = {{"frame_unique_thumpthump", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_vances9mmsmg"] = {time = 90, xp = 22, input = {{"frame_unique_vances9mmsmg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_weathered10mmpistol"] = {time = 90, xp = 22, input = {{"frame_unique_weathered10mmpistol", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["unique_ycs186"] = {time = 90, xp = 22, input = {{"frame_unique_ycs186", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["uzi"] = {time = 90, xp = 22, input = {{"frame_uzi", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["vertibird_designator"] = {time = 50, xp = 14, input = {{"frame_vertibird_designator", 1}, {"mat_steel", 2}, {"mat_circuitry", 1}}},
	["weapon_10mm_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_10mm_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_10mmsmg"] = {time = 90, xp = 22, input = {{"frame_weapon_10mmsmg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_127mm_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_127mm_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_127mmsmg"] = {time = 90, xp = 22, input = {{"frame_weapon_127mmsmg", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_22_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_22_pistol", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_25mm_grenade_launcher"] = {time = 90, xp = 22, input = {{"frame_weapon_25mm_grenade_launcher", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_357_revolver"] = {time = 70, xp = 18, input = {{"frame_weapon_357_revolver", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_44magnum"] = {time = 70, xp = 18, input = {{"frame_weapon_44magnum", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_45_auto_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_45_auto_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_50cal"] = {time = 90, xp = 22, input = {{"frame_weapon_50cal", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_556mmpistol"] = {time = 70, xp = 18, input = {{"frame_weapon_556mmpistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_9mm_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_9mm_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_9mmpistol_rusty"] = {time = 70, xp = 18, input = {{"frame_weapon_9mmpistol_rusty", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_9mmsmg"] = {time = 90, xp = 22, input = {{"frame_weapon_9mmsmg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_ak112"] = {time = 90, xp = 22, input = {{"frame_weapon_ak112", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_ak112_scoped"] = {time = 90, xp = 22, input = {{"frame_weapon_ak112_scoped", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_ak47"] = {time = 90, xp = 22, input = {{"frame_weapon_ak47", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_alien_blaster"] = {time = 90, xp = 22, input = {{"frame_weapon_alien_blaster", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_alien_disintegrator"] = {time = 90, xp = 22, input = {{"frame_weapon_alien_disintegrator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_antimaterialrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_antimaterialrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_arc_welder"] = {time = 90, xp = 22, input = {{"frame_weapon_arc_welder", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_assaultcarbine"] = {time = 90, xp = 22, input = {{"frame_weapon_assaultcarbine", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_automaticrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_automaticrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_battlerifle"] = {time = 90, xp = 22, input = {{"frame_weapon_battlerifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_bbgun"] = {time = 90, xp = 22, input = {{"frame_weapon_bbgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_brushgun"] = {time = 90, xp = 22, input = {{"frame_weapon_brushgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_caravanshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_caravanshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_caustic_shotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_caustic_shotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_chinese_assault_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_chinese_assault_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_chinese_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_chinese_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_cit_laser_pistol"] = {time = 90, xp = 22, input = {{"frame_weapon_cit_laser_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_cit_laser_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_cit_laser_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_combat_shotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_combat_shotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_cowboyrepeater"] = {time = 90, xp = 22, input = {{"frame_weapon_cowboyrepeater", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_deserteag"] = {time = 70, xp = 18, input = {{"frame_weapon_deserteag", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_double_barrel_shotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_double_barrel_shotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_enclave_plasma_gat"] = {time = 90, xp = 22, input = {{"frame_weapon_enclave_plasma_gat", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_fatman"] = {time = 90, xp = 22, input = {{"frame_weapon_fatman", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_fevspewer"] = {time = 90, xp = 22, input = {{"frame_weapon_fevspewer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_flamer"] = {time = 90, xp = 22, input = {{"frame_weapon_flamer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_fnfal"] = {time = 90, xp = 22, input = {{"frame_weapon_fnfal", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_gatling_laser"] = {time = 90, xp = 22, input = {{"frame_weapon_gatling_laser", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_gauss_musket"] = {time = 90, xp = 22, input = {{"frame_weapon_gauss_musket", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_gauss_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_gauss_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_gaussminigun"] = {time = 90, xp = 22, input = {{"frame_weapon_gaussminigun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_gobicampaignscoutrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_gobicampaignscoutrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_grenade_launcher"] = {time = 90, xp = 22, input = {{"frame_weapon_grenade_launcher", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_grenade_machine_gun"] = {time = 90, xp = 22, input = {{"frame_weapon_grenade_machine_gun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_grenade_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_grenade_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_hk_laser_gatling"] = {time = 90, xp = 22, input = {{"frame_weapon_hk_laser_gatling", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_hunting_revolver"] = {time = 70, xp = 18, input = {{"frame_weapon_hunting_revolver", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_huntingrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_huntingrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_huntingshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_huntingshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_imi_galil"] = {time = 90, xp = 22, input = {{"frame_weapon_imi_galil", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_incinerator"] = {time = 90, xp = 22, input = {{"frame_weapon_incinerator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_junk_jet"] = {time = 90, xp = 22, input = {{"frame_weapon_junk_jet", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_k9000_cyberdog"] = {time = 90, xp = 22, input = {{"frame_weapon_k9000_cyberdog", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_laer"] = {time = 90, xp = 22, input = {{"frame_weapon_laer", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_laser_pdw"] = {time = 90, xp = 22, input = {{"frame_weapon_laser_pdw", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_laser_pistol"] = {time = 90, xp = 22, input = {{"frame_weapon_laser_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_laser_rcw"] = {time = 90, xp = 22, input = {{"frame_weapon_laser_rcw", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_laser_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_laser_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_lasermusket"] = {time = 90, xp = 22, input = {{"frame_weapon_lasermusket", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_laserrifle_scoped"] = {time = 90, xp = 22, input = {{"frame_weapon_laserrifle_scoped", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_lasersmg"] = {time = 90, xp = 22, input = {{"frame_weapon_lasersmg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_leveractionshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_leveractionshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_lightmachinegun"] = {time = 90, xp = 22, input = {{"frame_weapon_lightmachinegun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_lockwood"] = {time = 90, xp = 22, input = {{"frame_weapon_lockwood", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_m14"] = {time = 90, xp = 22, input = {{"frame_weapon_m14", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_m60"] = {time = 90, xp = 22, input = {{"frame_weapon_m60", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_m72gaussrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_m72gaussrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_marksmancarbine"] = {time = 90, xp = 22, input = {{"frame_weapon_marksmancarbine", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_mg42"] = {time = 90, xp = 22, input = {{"frame_weapon_mg42", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_microwave_emitter"] = {time = 90, xp = 22, input = {{"frame_weapon_microwave_emitter", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_minigun"] = {time = 90, xp = 22, input = {{"frame_weapon_minigun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_missile_launcher"] = {time = 90, xp = 22, input = {{"frame_weapon_missile_launcher", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_mp5"] = {time = 90, xp = 22, input = {{"frame_weapon_mp5", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_mp5_sd"] = {time = 90, xp = 22, input = {{"frame_weapon_mp5_sd", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_mp5l"] = {time = 90, xp = 22, input = {{"frame_weapon_mp5l", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_multiplas"] = {time = 90, xp = 22, input = {{"frame_weapon_multiplas", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_nailgun"] = {time = 90, xp = 22, input = {{"frame_weapon_nailgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_navyrevolver"] = {time = 70, xp = 18, input = {{"frame_weapon_navyrevolver", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_plasma_caster"] = {time = 90, xp = 22, input = {{"frame_weapon_plasma_caster", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_plasma_defender"] = {time = 90, xp = 22, input = {{"frame_weapon_plasma_defender", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_plasma_pistol"] = {time = 90, xp = 22, input = {{"frame_weapon_plasma_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_plasma_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_plasma_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_plasmagatling"] = {time = 90, xp = 22, input = {{"frame_weapon_plasmagatling", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_police_pistol"] = {time = 70, xp = 18, input = {{"frame_weapon_police_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_r700"] = {time = 90, xp = 22, input = {{"frame_weapon_r700", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_r700_sup"] = {time = 90, xp = 22, input = {{"frame_weapon_r700_sup", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_r91"] = {time = 90, xp = 22, input = {{"frame_weapon_r91", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_ranger_sequoia"] = {time = 70, xp = 18, input = {{"frame_weapon_ranger_sequoia", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_recharger_pistol"] = {time = 90, xp = 22, input = {{"frame_weapon_recharger_pistol", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_recharger_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_recharger_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_riotshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_riotshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_sawedoffshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_sawedoffshotgun", 1}, {"mat_steel", 2}, {"mat_screws", 2}}},
	["weapon_service_rifle_automatic"] = {time = 90, xp = 22, input = {{"frame_weapon_service_rifle_automatic", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_servicerifle"] = {time = 90, xp = 22, input = {{"frame_weapon_servicerifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_shouldermountedshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_shouldermountedshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_silenced22smg"] = {time = 90, xp = 22, input = {{"frame_weapon_silenced22smg", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_singleshotgun"] = {time = 90, xp = 22, input = {{"frame_weapon_singleshotgun", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_sniperrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_sniperrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_tesla_cannon"] = {time = 90, xp = 22, input = {{"frame_weapon_tesla_cannon", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_tesla_rcw"] = {time = 90, xp = 22, input = {{"frame_weapon_tesla_rcw", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_teslacaster"] = {time = 90, xp = 22, input = {{"frame_weapon_teslacaster", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_teslasniperrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_teslasniperrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_trailcarbine"] = {time = 90, xp = 22, input = {{"frame_weapon_trailcarbine", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_tribeam_laser_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_tribeam_laser_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_turboplasma_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_turboplasma_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_varmintrifle"] = {time = 90, xp = 22, input = {{"frame_weapon_varmintrifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_vindicator"] = {time = 90, xp = 22, input = {{"frame_weapon_vindicator", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["weapon_wattz_laser_rifle"] = {time = 90, xp = 22, input = {{"frame_weapon_wattz_laser_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}, {"mat_circuitry", 2}, {"mat_crystal", 1}}},
	["weapon_yk42b"] = {time = 90, xp = 22, input = {{"frame_weapon_yk42b", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
	["xm8_rifle"] = {time = 90, xp = 22, input = {{"frame_xm8_rifle", 1}, {"mat_steel", 4}, {"mat_screws", 2}, {"mat_springs", 2}}},
}
