--[[
	Race injectors: becoming something else, for a while or for good.

	Phoenix's `drugs_simple` has three of these - a behemoth, a centaur and a
	unity behemoth - and each is an aid item whose effect calls
	`nut.races:transform`: freeze the player, scale the model, throw an effect
	every second for nine seconds, then swap the race. It is the most theatrical
	thing in their schema and it is worth having in full.

	    permanent    the character IS that race afterwards. It is written to
	                 the database like any other race change
	    temporary    the character goes back on its own, and the deadline is
	                 wall-clock so a restart does not extend or cancel it

	ONE ITEM PER RACE, IN BOTH KINDS, generated by `_docs/tools/geninjectors.py`
	from the race roster - so a new race is a new pair of items the moment the
	generator is run rather than a file somebody has to remember to write.

	NOT EVERYTHING IS AN INJECTOR. You do not inject somebody into being a
	Securitron; the robot races get a `Conversion Kit` instead, and the human
	one is an `Anti-Mutagen Serum` - a cure rather than a dose. The naming is
	the generator's, and the rules for it are written at the top of that file.

	THEY ARE AID ITEMS. `items/base/sh_injector.lua` has `base_aid` as its own
	base, so an injector inherits Use, the five-second staring Inject that puts
	one into somebody else, the chem whitelists, the power-armour rule and the
	sound - all of which already work and none of which is about races.
]]

ix.raceinject = ix.raceinject or {}

--[[
	How long the transformation itself takes.

	Phoenix's is nine seconds of effect with the change at the end, which is
	long enough to be an event other people walk over to watch and short enough
	that nobody minds being frozen for it. Configurable because it is a pace
	decision rather than a technical one.
]]
ix.config.Add("injectorTransformTime", 9,
	"Seconds a race injection takes before the change happens.", nil, {
	data = {min = 1, max = 60},
	category = "Injectors"
})

--[[
	A TEMPORARY INJECTION LASTS ONE LIFE, not a number of minutes.

	It was a timer, and a life is the better unit for two reasons. It is
	Phoenix's - their temporary races are cleared when the character dies -
	and it makes the thing an event with an ending somebody can see coming:
	you are a deathclaw until something kills you, rather than until a clock
	nobody can read runs out mid-fight.

	A DEADLINE IS STILL SUPPORTED and is what an item asking for one gets - see
	`ITEM.duration` - because "a nightkin for ten minutes" is a reasonable thing
	for one specific item to be. Nothing ships set that way.
]]
ix.config.Add("injectorDuration", 0,
	"Seconds a temporary race injection lasts. 0 means one life.", nil, {
	data = {min = 0, max = 86400},
	category = "Injectors"
})

--[[
	Whether somebody else has to be TIED UP before you can change what they are.

	ON, and it is the rule rather than a prompt. A chem can be pushed into
	anybody who will stand still for five seconds, which is fine for a stimpak
	and not fine for something that rewrites what they are for good - so a race
	injection needs them restrained, and restraining somebody is already a
	whole interaction with its own items, timings and counterplay
	(`37-restraints.md`).

	It says the thing a consent prompt would say, without a prompt: if they did
	not agree to this, somebody had to tie them up first.

	Injecting YOURSELF is never gated by it.
]]
ix.config.Add("injectorNeedsRestrained", true,
	"Whether somebody has to be restrained before you can race-inject them.",
	nil, {
	category = "Injectors"
})

--[[
	Seconds a temporary injection lasts, or 0 for "until you die".

	The item's own `duration` wins, then the config, and 0 from both means one
	life. Callers pass this straight to `ix.raceinject.Begin`, which reads 0 as
	the life-long kind rather than as "no time at all" - the item having said
	`temporary` is what separates the two.
]]
function ix.raceinject.Duration(itemTable)
	local own = itemTable and itemTable.duration

	if (own and own > 0) then return own end

	return math.max(math.floor(ix.config.Get("injectorDuration", 0)), 0)
end

--[[
	What a character will turn back into, and when. `nil` when nothing is
	pending.

	Stored on the CHARACTER rather than on the player, so it survives a
	disconnect - and as `os.time`, so it survives a restart. `CurTime` restarts
	at zero with the map, which would either cancel a transformation or make it
	permanent depending on which way the arithmetic fell (gotcha 11).
]]
function ix.raceinject.Pending(character)
	if (not character) then return nil end

	local pending = character:GetData("raceRevert")

	if (not istable(pending) or not pending.race) then return nil end
	if (not ix.races.list[pending.race]) then return nil end

	--[[
		`at` of 0 means there is no deadline and it ends with the life - the
		tick skips those and `PlayerDeath` handles them. Returned as the third
		value so a caller can tell the two apart without reading the data
		itself.
	]]
	local at = tonumber(pending.at) or 0

	return pending.race, at, at <= 0
end
