--[[
	Logging the things that get argued about.

	Helix registers exactly ONE log type of its own - `charMoneyGive` - so a
	server running it has no record of who picked up what, who dropped what,
	who moved money, or what anybody said. Every question an admin actually
	gets asked is about one of those.

	    every money change      with the before, the after and the reason
	    every item transfer     between which two inventories, and whose
	    every item spawned      and every item picked up off the floor
	    every weapon drawn
	    every chat line
	    every connect, character load and death

	MONEY IS WRAPPED, NOT HOOKED, because there is no hook. `SetMoney` is the
	single funnel every path goes through - a shop sale, a `/givemoney`, a
	salary, an admin's `/charsetmoney` - so wrapping it once catches all of
	them, including ones written later that nobody remembered to log.

	THE REASON IS INFERRED FROM WHAT ELSE IS HAPPENING, and that is a
	deliberate limit rather than a guess dressed up: `ix.tracking.reason` is
	set for the duration of an operation that knows why it is moving money and
	cleared afterwards. Anything that does not set it is logged as "unknown",
	which is honest and still tells you the amount, the character and the time.
]]

if (not SERVER) then return end

ix.tracking = ix.tracking or {}

--[[
	Why money is moving right now, if anything knows.

	A single value rather than a stack: money moves synchronously inside one
	operation, so there is never a second reason waiting behind the first.
]]
ix.tracking.reason = nil

--- Run something with a reason attached, and clear it however that ends.
function ix.tracking.With(reason, callback)
	ix.tracking.reason = reason

	local ok, err = pcall(callback)

	ix.tracking.reason = nil

	if (not ok) then error(err) end
end

--------------------------------------------------------------------------------
-- Money
--------------------------------------------------------------------------------

local function WrapMoney()
	local characterMeta = ix.meta.character

	if (not characterMeta) then return false end

	--[[
		`SetMoney` is GENERATED by `ix.char.RegisterVar("money")` rather than
		written out, so it exists only once that has run. At schema load it
		normally already has - but "normally" is not a guarantee worth a silent
		hole in the money log, so this returns false and is retried.
	]]
	local original = characterMeta.SetMoney

	if (not original) then return false end

	--[[
		Wrapped once. The guard is what stops a `lua_refresh` wrapping the
		wrapper around itself and logging every change twice - which reads as
		two people moving money rather than one.
	]]
	if (characterMeta.ixTracked) then return true end

	characterMeta.ixTracked = true

	function characterMeta:SetMoney(amount)
		local before = self:GetMoney() or 0

		original(self, amount)

		local after = self:GetMoney() or 0

		if (before == after) then return end

		ix.log.Add(self:GetPlayer(), "moneyChange", self:GetName(),
			self:GetID(), before, after, after - before,
			ix.tracking.reason or "unknown")
	end

	return true
end

if (not WrapMoney()) then
	hook.Add("InitializedPlugins", "ixTrackingMoney", function()
		if (not WrapMoney()) then
			ErrorNoHalt("[falloutrp] character SetMoney never appeared - "
				.. "money changes are NOT being logged\n")
		end
	end)
end

ix.log.AddType("moneyChange", function(client, name, charID, before, after,
	delta, reason)
	return string.format(
		"%s (char %d) %s %s - %s to %s [%s]%s", name, charID,
		delta > 0 and "gained" or "lost",
		ix.currency.Get(math.abs(delta)), ix.currency.Get(before),
		ix.currency.Get(after), reason,
		IsValid(client) and (" " .. client:SteamID()) or "")
end, FLAG_WARNING)

--------------------------------------------------------------------------------
-- Items
--------------------------------------------------------------------------------

--[[
	Naming an inventory in a way an admin can act on.

	An inventory id alone is a number nobody can look up later. Whose it is, or
	what container it belongs to, is the thing that turns "item 4471 moved from
	12 to 88" into "Bob gave it to Alice".

	`ix.item.inventories[0]` IS A BARE TABLE, NOT AN INVENTORY.

	Helix uses index 0 to mean "the world" and stores a plain `{}` there - no
	metatable, so no `GetOwner`, no `GetID`, no anything. This called
	`inventory:GetOwner()` straight out and threw on every single transfer that
	touched the world, which is every item picked up off the ground and every
	item dropped onto it.

	AND THE THROW WAS THE REAL DAMAGE. `OnItemTransferred` is fired from inside
	`ITEM:Transfer`, which is inside the take function, which is inside
	`ix.item.PerformInventoryAction` - and an error in a hook takes all three
	down with it. The item had already been added to its new inventory by then;
	what never ran was the rest of `Transfer`, the `return true`, and

	    if (result != false) then
	        if (IsValid(entity)) then entity.ixIsSafe = true entity:Remove()

	which is what removes the entity from the ground. So a picked-up item was
	in the inventory AND still lying there, pressing E on it a second time
	answered "same inv", and dropping it hit `item.entity:GetPos()` on an
	entity that had since been removed. Three unrelated-looking faults from one
	unguarded method call in a LOG LINE.

	Nothing that only writes a log entry may ever be able to do that, so this
	answers "the world" for anything without the methods rather than assuming
	it has them.
]]
local function Describe(inventory)
	if (not inventory or not inventory.GetID) then return "the world" end

	local owner = inventory.GetOwner and inventory:GetOwner()
	local vars = inventory.vars or {}

	--[[
		A PACK BY NAME. A pack's storage belongs to the character carrying
		it, so the owner test below called it the character, and a stimpak
		put into a pack "moved from <character> to <character>".
	]]
	if (isstring(vars.isBag) and ix.backpack and ix.backpack.ItemOf) then
		local pack = ix.backpack.ItemOf(inventory)

		if (pack) then
			local held = IsValid(owner) and owner:IsPlayer() and owner:GetCharacter()

			return string.format("the %s (item %d)%s", pack:GetName(), pack.id,
				held and string.format(" of %s (char %d)", owner:Name(), held:GetID()) or "")
		end
	end

	if (IsValid(owner) and owner:IsPlayer()) then
		local character = owner:GetCharacter()

		return string.format("%s (char %d)", owner:Name(),
			character and character:GetID() or 0)
	end

	if (vars.bench) then
		return string.format("bench %d", vars.bench)
	end

	if (vars.factionStorage) then
		return string.format("faction storage %d", vars.factionStorage)
	end

	if (vars.trash) then
		return string.format("the bin of char %d", vars.trash)
	end

	return string.format("inventory %d", inventory:GetID() or 0)
end

--[[
	The whole hook, wrapped so a log line can never break a transfer again.

	The bug above was one nil call; the LESSON is that anything hanging off
	`OnItemTransferred` runs inside somebody else's transaction. A `pcall` here
	costs nothing measurable and turns "the log line was wrong" back into what
	it should always have been: a wrong log line.
]]
local function Safely(fn, ...)
	local ok, err = pcall(fn, ...)

	if (not ok) then
		ErrorNoHalt(string.format("[falloutrp] item tracking failed, and the "
			.. "transfer carried on regardless: %s\n", tostring(err)))
	end
end

--[[
	EVERY transfer, including the ones inside one inventory.

	Moving an item from one slot to another is not interesting on its own, so
	it is skipped - but a transfer BETWEEN inventories is the single most
	useful line in the whole log, because it is what item laundering looks
	like.
]]
hook.Add("OnItemTransferred", "ixTracking", function(item, from, to)
	if (from == to) then return end

	Safely(function()
		local client = item.player

		if (not IsValid(client) and to) then
			local owner = to.GetOwner and to:GetOwner()

			if (IsValid(owner) and owner:IsPlayer()) then client = owner end
		end

		ix.log.Add(client, "itemMove", item.name, item.id, item.uniqueID,
			Describe(from), Describe(to), ix.stack.Get(item))
	end)
end)

ix.log.AddType("itemMove", function(client, name, id, uniqueID, from, to,
	quantity)
	return string.format("%s (item %d, %s)%s moved from %s to %s%s", name, id,
		uniqueID, quantity > 1 and (" x" .. quantity) or "", from, to,
		IsValid(client) and (" - by " .. client:Name()) or "")
end)

hook.Add("OnItemSpawned", "ixTracking", function(entity)
	local item = entity.GetItemTable and entity:GetItemTable()

	if (not item) then return end

	ix.log.Add(nil, "itemWorld", item.name, item.id, item.uniqueID,
		tostring(entity:GetPos()))
end)

ix.log.AddType("itemWorld", function(client, name, id, uniqueID, position)
	return string.format("%s (item %d, %s) is now on the ground at %s", name,
		id, uniqueID, position)
end)

--[[
	Equipping is logged from the WEAPON CHANGING, not from
	`CanPlayerEquipItem`.

	That hook lives inside the item function's `OnCanRun`, which Helix calls
	every time it builds a right-click menu - so logging there would write a
	line every time anybody looked at a gun, and a log that is mostly noise is
	a log nobody reads. `PlayerWeaponChanged` fires when something actually
	happened.
]]
hook.Add("PlayerWeaponChanged", "ixTracking", function(client, weapon)
	if (not IsValid(weapon)) then return end

	local item = weapon.ixItem

	ix.log.Add(client, "weaponDrawn", weapon:GetClass(),
		item and item.name or weapon:GetPrintName() or "",
		item and item.id or 0)
end)

ix.log.AddType("weaponDrawn", function(client, class, name, id)
	return string.format("%s drew %s%s.", client:Name(),
		name ~= "" and name or class,
		id > 0 and string.format(" (item %d)", id) or "")
end)

--------------------------------------------------------------------------------
-- People
--------------------------------------------------------------------------------

hook.Add("PostPlayerSay", "ixTracking", function(client, text, chatType)
	ix.log.Add(client, "chatLine", chatType or "ic", text)
end)

ix.log.AddType("chatLine", function(client, chatType, text)
	return string.format("[%s] %s: %s", chatType, client:Name(), text)
end)

--[[
	CHARACTER LOADS, CREATIONS, DELETIONS, DEATHS, CONNECTS AND DISCONNECTS
	ARE NOT LOGGED HERE, and it is worth writing down why not.

	Helix's own `plugins/logging.lua` already registers `charLoad`,
	`charCreate`, `charDelete`, `playerDeath`, `connect` and `disconnect`.
	Registering a type that already exists REPLACES its formatter - so ours
	took over, and then Helix's plugin called it with ITS arguments:

	    ix.log.Add(client, "charLoad", character:GetName())   -- one argument
	    function(client, name, id, steamID) ... "%d" ... id   -- three expected

	which is `bad argument #4 to 'text' (number expected, got nil)` on every
	character load, from inside `character:Setup()`.

	Their versions cover the same ground. Everything else in this file logs
	something nothing else does, which is the only reason for any of it to
	exist - see the collision guard in `sv_adminlog.lua`.
]]
