--[[
	Mutfruit.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Mutfruit"
ITEM.description = "Tasty fresh produce."
ITEM.model = "models/mosi/fallout4/props/food/mutfruit.mdl"

ITEM.sustenance = 15
ITEM.radiation = 1

ITEM.eatMeText = "chews on some raw Mutfruit . . ."
