--[[
	Honey Mesquite.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Honey Mesquite"
ITEM.description = "The honey mesquite pod grows on a short tree with "
	.. "willow-like branches."
ITEM.model = "models/roadkill/fallout/clutter/plants/honey_mesquite_fruit.mdl"

ITEM.radiation = 5

ITEM.eatMeText = "chews on some raw Honey Pods . . ."

ITEM.chemHint = true
