--[[
	Pinto Pod.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Pinto Pod"
ITEM.description = "A pod of Pinto beans."
ITEM.model = "models/roadkill/fallout/clutter/plants/pinto_root_fruit.mdl"

ITEM.sustenance = 10
ITEM.radiation = 5

ITEM.eatMeText = "chews on some raw Pinto Pods . . ."

ITEM.heal = {1, 1, 10}
ITEM.chemHint = true
