--[[
	Maize.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Maize"
ITEM.description = "A stalk of maize."
ITEM.model = "models/roadkill/fallout/clutter/plants/maize_fruit.mdl"

ITEM.sustenance = 20
ITEM.radiation = 10

ITEM.eatMeText = "chews on some raw Maize . . ."

ITEM.heal = {1, 1, 10}
