--[[
	Prickly Pear.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Prickly Pear"
ITEM.description = "A sweet fruit harvested from a prickly pear cactus."
ITEM.model = "models/roadkill/fallout/clutter/plants/prickly_pear_cactus_fruit.mdl"


ITEM.eatMeText = "chews on some raw Prickly Pear . . ."

ITEM.hallucinate = 40
