--[[
	Nevada Agave.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Nevada Agave"
ITEM.description = "A rare wasteland plant often used for healing skin "
	.. "blemishes."
ITEM.model = "models/roadkill/fallout/clutter/plants/nevada_agave_fruit.mdl"

ITEM.sustenance = 10
ITEM.radiation = 5

ITEM.eatMeText = "chews on some raw Nevada Agave . . ."

ITEM.heal = {1, 1, 10}
ITEM.chemHint = true
