--[[
	Brain Fungus.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Brain Fungus"
ITEM.description = "Looks like it might make for a tasty snack."
ITEM.model = "models/roadkill/fallout/clutter/plants/brain_fungus_fungus.mdl"

ITEM.radiation = 10

ITEM.eatMeText = "chews on some strange Fungus . . ."

ITEM.knockout = 15
ITEM.chemHint = true
