--[[
	White Horsenettle.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "White Horsenettle"
ITEM.description = "A bunch of Horsenettle seeds."
ITEM.model = "models/roadkill/fallout/clutter/plants/whitehorse_berrys.mdl"

ITEM.sustenance = 10
ITEM.radiation = 4

ITEM.eatMeText = "chews on a bunch of random seeds . . ."
