--[[
	Carrot.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Carrot"
ITEM.description = "Tasty fresh produce."
ITEM.model = "models/mosi/fnv/props/food/crops/carrot.mdl"

ITEM.sustenance = 10
ITEM.radiation = 1

ITEM.eatMeText = "chews on some raw Carrot . . ."
