--[[
	Jalapeño.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Jalapeño"
ITEM.description = "A very hot pepper."
ITEM.model = "models/roadkill/fallout/clutter/plants/jalepeno_root_fruit.mdl"

ITEM.sustenance = 10
ITEM.radiation = 4

ITEM.eatMeText = "chews on some raw Jalapeño . . ."

ITEM.ignite = {5, 10}
ITEM.chemHint = true
