--[[
	Broc Flower.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Broc Flower"
ITEM.description = "A resilient blossom, known for its natural healing "
	.. "qualities."
ITEM.model = "models/roadkill/fallout/clutter/plants/brocflower_bud.mdl"


ITEM.eatMeText = "chews on some raw Broc Flower . . ."

ITEM.chemHint = true
