--[[
	Buffalo Gourd.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Buffalo Gourd"
ITEM.description = "A 'seed' from a Buffalo Gourd plant."
ITEM.model = "models/roadkill/fallout/clutter/plants/buffalo_guord_fruit.mdl"

ITEM.sustenance = 10
ITEM.radiation = 5

ITEM.eatMeText = "tears open and devours an entire Melon . . ."

ITEM.heal = {1, 1, 10}
