--[[
	Barrel Cactus.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Barrel Cactus"
ITEM.description = "A sweet fruit harvested from a barrel cactus."
ITEM.model = "models/roadkill/fallout/clutter/plants/barrel_cactus_fruit.mdl"


ITEM.eatMeText = "chews on some raw Barrel Cactus Fruit . . ."

ITEM.hallucinate = 60
