--[[
	Coyote Tobacco.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Coyote Tobacco"
ITEM.description = "Even odds of either shrugging off blows for two "
	.. "minutes or falling unconscious."
ITEM.model = "models/roadkill/fallout/clutter/plants/coyote_tobacco_fruit.mdl"

ITEM.radiation = 3

ITEM.eatMeText = "chews on some raw Coyote Tobacco . . ."

ITEM.gamble = {chance = 0.5, stat = "DR", value = 10,
	duration = 120, knockout = 15}
ITEM.chemHint = true
