--[[
	Sacred Datura.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Sacred Datura"
ITEM.description = "A flowering plant with psychoactive properties. Often "
	.. "used in rituals and rites of passage."
ITEM.model = "models/roadkill/fallout/clutter/plants/sacred_datura_flower.mdl"

ITEM.radiation = 5

ITEM.eatMeText = "chews on some raw Sacred Datura . . ."

ITEM.hallucinate = 60
