--[[
	Cave Fungus.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Cave Fungus"
ITEM.description = "Fungus pulled off a cave wall. It smells like the cave."
ITEM.model = "models/roadkill/fallout/clutter/plants/cave_fungus_fungus.mdl"

ITEM.radiation = 20

ITEM.eatMeText = "chews on some strange Fungus . . ."

ITEM.knockout = 15
