--[[
	Banana Yucca.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Banana Yucca"
ITEM.description = "A nutritious plant with medicinal effects."
ITEM.model = "models/roadkill/fallout/clutter/plants/banana_yucca_fruit.mdl"

ITEM.radiation = 3

ITEM.eatMeText = "chews on some raw Banana Yucca . . ."

ITEM.heal = {1, 1, 10}
ITEM.chemHint = true
