--[[
	Xander Root.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Xander Root"
ITEM.description = "A hardy desert herb with medicinal properties."
ITEM.model = "models/roadkill/fallout/clutter/plants/xanderroot_model.mdl"

ITEM.sustenance = 10
ITEM.radiation = 10

ITEM.eatMeText = "chews on some raw Xanderroot . . ."

ITEM.heal = {1, 1, 10}
ITEM.chemHint = true
