--[[
	Tarberry.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Tarberry"
ITEM.description = "Tasty fresh produce."
ITEM.model = "models/mosi/fallout4/props/food/tarberry.mdl"

ITEM.sustenance = 10
ITEM.radiation = 1

ITEM.eatMeText = "chews on some raw Tarberry . . ."
