--[[
	Broc Flower seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Broc Flower Seeds"
ITEM.description = "A bag of broc flower seeds."

ITEM.plantType = "plant_brocflower"
