--[[
	Mutfruit seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Mutfruit Seeds"
ITEM.description = "A bag of mutfruit seeds."

ITEM.plantType = "plant_mutfruit"
