--[[
	Honey Mesquite seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Honey Mesquite Seeds"
ITEM.description = "A bag of honey mesquite seeds."

ITEM.plantType = "plant_honeymesquite"
