--[[
	Nevada Agave seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Nevada Agave Seeds"
ITEM.description = "A bag of nevada agave seeds."

ITEM.plantType = "plant_nevadaagave"
