--[[
	Jalapeño seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Jalapeño Seeds"
ITEM.description = "A bag of jalapeño seeds."

ITEM.plantType = "plant_jalapeno"
