--[[
	Cave Fungus seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Cave Fungus Seeds"
ITEM.description = "A bag of cave fungus seeds."

ITEM.plantType = "plant_cavefungus"
