--[[
	Barrel Cactus seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Barrel Cactus Seeds"
ITEM.description = "A bag of barrel cactus seeds."

ITEM.plantType = "plant_barrelcactus"
