--[[
	White Horsenettle seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "White Horsenettle Seeds"
ITEM.description = "A bag of white horsenettle seeds."

ITEM.plantType = "plant_whitehorsenettle"
