--[[
	Pinto Root seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Pinto Root Seeds"
ITEM.description = "A bag of pinto root seeds."

ITEM.plantType = "plant_pintoroot"
