--[[
	Tarberry seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Tarberry Seeds"
ITEM.description = "A bag of tarberry seeds."

ITEM.plantType = "plant_tarberry"
