--[[
	Coyote Tobacco seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Coyote Tobacco Seeds"
ITEM.description = "A bag of coyote tobacco seeds."

ITEM.plantType = "plant_coyotetobacco"
