--[[
	Banana Yucca seeds.

	Generated by `_docs/tools/genplants.py` from Phoenix's own numbers - edit
	the table there rather than this file, or the next run will overwrite you.
]]

ITEM.name = "Banana Yucca Seeds"
ITEM.description = "A bag of banana yucca seeds."

ITEM.plantType = "plant_bananayucca"
