-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Armored Feral Ghoul Injector"
ITEM.description = "A dose of stabilised armored feral ghoul genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_armored"
ITEM.temporary = false
