-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Feral Ghoul Reaver Injector"
ITEM.description = "A dose of stabilised feral ghoul reaver genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_reaver"
ITEM.temporary = false
