-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Radscorpion Injector"
ITEM.description = "A dose of unfixed radscorpion genetic material. It takes, "
	.. "and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radscorpion"
ITEM.temporary = true
