-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Unity Behemoth Injector"
ITEM.description = "A dose of unfixed unity behemoth genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "behemoth_unity"
ITEM.temporary = true
