-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Roboscorpion Conversion Kit"
ITEM.description = "A field rig that rebuilds a body into a Roboscorpion. "
	.. "There is no reversing the wiring afterwards."
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"

ITEM.race = "roboscorpion"
ITEM.temporary = false
