-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Temporary Securitron Executive Conversion Kit"
ITEM.description = "A field rig that drives a body through a Securitron "
	.. "Executive chassis pattern. The frame gives out and lets "
	.. "you go."
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"

ITEM.race = "securitronexecutive"
ITEM.temporary = true
