-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Giant Ant Injector"
ITEM.description = "A dose of stabilised giant ant genetic material. What it "
	.. "does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "giantant"
ITEM.temporary = false
