-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Generation 1 Synth Injector"
ITEM.description = "A dose of unfixed generation 1 synth genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "citgen1"
ITEM.temporary = true
