-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Centaur Injector"
ITEM.description = "A dose of stabilised centaur genetic material. What it "
	.. "does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "centaur"
ITEM.temporary = false
