-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Nuka Radscorpion Injector"
ITEM.description = "A dose of stabilised nuka radscorpion genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radscorpion_nuka"
ITEM.temporary = false
