-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Green Gecko Injector"
ITEM.description = "A dose of unfixed green gecko genetic material. It takes, "
	.. "and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "geckogreen"
ITEM.temporary = true
