-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Nuka Radroach Injector"
ITEM.description = "A dose of stabilised nuka radroach genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radroach_nuka"
ITEM.temporary = false
