-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Frank Horrigan Injector"
ITEM.description = "A dose of stabilised frank horrigan genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "frankhorrigan"
ITEM.temporary = false
