-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Armored Feral Ghoul Injector"
ITEM.description = "A dose of unfixed armored feral ghoul genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_armored"
ITEM.temporary = true
