-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Centaur Evolved Injector"
ITEM.description = "A dose of stabilised centaur evolved genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "centaur_evolved"
ITEM.temporary = false
