-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Spore Carrier Injector"
ITEM.description = "A dose of unfixed spore carrier genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "sporecarrier"
ITEM.temporary = true
