-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unity Behemoth Injector"
ITEM.description = "A dose of stabilised unity behemoth genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "behemoth_unity"
ITEM.temporary = false
