-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Glowing One Injector"
ITEM.description = "A dose of stabilised glowing one genetic material. What it "
	.. "does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_glowing"
ITEM.temporary = false
