-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Anti-Mutagen Serum"
ITEM.description = "A thin serum that argues your cells back into the shape "
	.. "they were born in, and wins."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "human"
ITEM.temporary = false
