-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Feral Ghoul Reaver Injector"
ITEM.description = "A dose of unfixed feral ghoul reaver genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_reaver"
ITEM.temporary = true
