-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Nuka Radroach Injector"
ITEM.description = "A dose of unfixed nuka radroach genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radroach_nuka"
ITEM.temporary = true
