-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Glowing One Injector"
ITEM.description = "A dose of unfixed glowing one genetic material. It takes, "
	.. "and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "feralghoul_glowing"
ITEM.temporary = true
