-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Frank Horrigan Injector"
ITEM.description = "A dose of unfixed frank horrigan genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "frankhorrigan"
ITEM.temporary = true
