-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Deathclaw Baby Injector"
ITEM.description = "A dose of unfixed deathclaw baby genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "deathclaw_baby"
ITEM.temporary = true
