-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Temporary Robobrain Conversion Kit"
ITEM.description = "A field rig that drives a body through a Robobrain chassis "
	.. "pattern. The frame gives out and lets you go."
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"

ITEM.race = "robobrain"
ITEM.temporary = true
