-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Giant Ant Injector"
ITEM.description = "A dose of unfixed giant ant genetic material. It takes, "
	.. "and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "giantant"
ITEM.temporary = true
