-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Behemoth Injector"
ITEM.description = "A dose of stabilised behemoth genetic material. What it "
	.. "does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "behemoth"
ITEM.temporary = false
