-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Glowing Radscorpion Injector"
ITEM.description = "A dose of stabilised glowing radscorpion genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radscorpion_glowing"
ITEM.temporary = false
