-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Super Mutant Injector"
ITEM.description = "A dose of stabilised super mutant genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "supermutant"
ITEM.temporary = false
