-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Deathclaw Matriarch Injector"
ITEM.description = "A dose of unfixed deathclaw matriarch genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "deathclaw_matriarch"
ITEM.temporary = true
