-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Temporary Roboscorpion Conversion Kit"
ITEM.description = "A field rig that drives a body through a Roboscorpion "
	.. "chassis pattern. The frame gives out and lets you go."
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"

ITEM.race = "roboscorpion"
ITEM.temporary = true
