-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Generation 2 Synth Injector"
ITEM.description = "A dose of stabilised generation 2 synth genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "citgen2"
ITEM.temporary = false
