-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Sentry Bot Conversion Kit"
ITEM.description = "A field rig that rebuilds a body into a Sentry Bot. There "
	.. "is no reversing the wiring afterwards."
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"

ITEM.race = "sentrybot"
ITEM.temporary = false
