-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Deathclaw Matriarch Injector"
ITEM.description = "A dose of stabilised deathclaw matriarch genetic material. "
	.. "What it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "deathclaw_matriarch"
ITEM.temporary = false
