-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Legion Mongrel Injector"
ITEM.description = "A dose of unfixed legion mongrel genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "legion_mongrel"
ITEM.temporary = true
