-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Legion Mongrel Injector"
ITEM.description = "A dose of stabilised legion mongrel genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "legion_mongrel"
ITEM.temporary = false
