-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Spore Carrier Injector"
ITEM.description = "A dose of stabilised spore carrier genetic material. What "
	.. "it does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "sporecarrier"
ITEM.temporary = false
