-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Centaur Evolved Injector"
ITEM.description = "A dose of unfixed centaur evolved genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "centaur_evolved"
ITEM.temporary = true
