-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Legatus Injector"
ITEM.description = "A dose of stabilised legatus genetic material. What it "
	.. "does to you, it keeps."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "legion_legatus"
ITEM.temporary = false
