-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Super Mutant Injector"
ITEM.description = "A dose of unfixed super mutant genetic material. It takes, "
	.. "and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "supermutant"
ITEM.temporary = true
