-- Generated by _docs/tools/geninjectors.py - do not edit by hand.

ITEM.name = "Unstable Glowing Radscorpion Injector"
ITEM.description = "A dose of unfixed glowing radscorpion genetic material. It "
	.. "takes, and then it lets go."
ITEM.model = "models/mosi/fallout4/props/junk/injector.mdl"

ITEM.race = "radscorpion_glowing"
ITEM.temporary = true
